# Generated by Django 3.2.2 on 2021-07-13 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100000)], verbose_name='Price'),
        ),
    ]
