# Generated by Django 3.2.2 on 2021-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productspage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_amount',
            field=models.FloatField(null=True),
        ),
    ]
